db: 'mongodb'
pageSize: 10
topListSize: 5
reminderTaskDelay: 36000 #30 minutes
teleportDelay: 30 #ticks
apiUrlName: 'https://api.mojang.com/user/profiles/{0}/names'
apiUrlUUID: 'https://api.mojang.com/users/profiles/minecraft/{0}'
sql:
  user: root
  password: ''
  database: 'minebench'
  url: 'localhost:3306'
  tables:
    tickets: 'st_tickets'
    comments: 'st_comments'
    players: 'st_players'
mongo:
  host: 'localhost'
  port: 27017
  database: 'SupportTickets'
  collection: 'SupportTickets'